### ISSUE TITLE
KSPedia shows wrong value

### ISSUE THREAD

**Issue by macrojames** [Galileo88/Galileos-Planet-Pack#35]
KSPedia entry  for Eta shows a threshold of 80km for low space. In fact it is 30km.

**Comment by Poodmund** [comment]
I would like to point you to the Known Issues section of the Readme: https://github.com/Galileo88/Galileos-Planet-Pack/blob/master/README.md 

Unfortunately you are correct and there is a fair bit of information that is required to be changed. This will be rectified for the next major release version. 

Thank you for raising the issue.

*Note to other Devs: Yes the issue is known but until it is rectified I will leave this open.

**Comment by Poodmund** [comment]
Fixed all values in the latest 1.6.0 update. Please comment if you fixed any further errors we missed.
