### ISSUE TITLE
Thermal runaway in warp

### ISSUE THREAD

**Issue by spexgaelen** [Galileo88/Galileos-Planet-Pack#66]
After upgrading to KSP 1.9.1 and GPP 1.6.5.0 my saved career game vessels around Thalia are not really usable in warp. 

Switching to the vessels starts with extremely high temperatures, the radiators kick in and usually everything cools off. Previously everything would start at a relatively cool (if not oddly cold) state when switching in. 

But what is worse is that time warping more than the first few ticks causes the vessels to overheat and explode as soon as timewarp is turned off.

Is this a change to KSP or to GPP? Is there some work-around I can apply (other than making ships indestructible through cheats)?

I haven't even dared to check on my vessels at Icarus.

Love this mod. Thanks for all your efforts making and supporting it. It looks really great in KSP 1.9.1.

-s

**Comment by JadeOfMaar** [comment]
Thalia has a radioactive/thermal hazard around it by design. The feature has been broken for a long time because the plugin or module for it was obsolete and just recently replaced/fixed. If you go into the highest two levels of timewarp, heat calculation mechanics break (that's a stock bug). But it's good practice to bring more radiator than you need because timewarp calculations get weird anyway, like with battery usage.

**Comment by spexgaelen** [comment]
Thanks for the prompt reply!

And ah, ok. The high-warp problem and the now working hazard can probably explain the rather sudden onset of thermal problems.

What I'm not super clear on, though, is how switching vessels now starts so hot. But that's probably a change to KSP.
